perf!: replace error strings by custom errors + use `enum` for `OPERATION_TYPE`
ERC725Alliance/ERC725 pull request #175
Opened 2022-10-20 15:56 UTC by CJ42

# What does this PR introduce?

## ♻️ Refactor (⚠️ BREAKING CHANGES)

- replace revert reason strings by custom errors in `ERC725XCore` and `ERC725YCore`. All errors are listed in `errors.sol`.

This reduces the deployment cost of the contracts by around 200,00 gas. See table summary below.

- replace the `uint256` constants for each OPERATION_TYPE by an enum -> this change requires type casting for comparing the `uint256 operationType` passed as parameter, but improve readability of the ERC725X contract code.

## 🎨 Style

- delete comments that aim to create sections _e.g: public functions, internal functions, overriden functions, etc...)_. Remove these comments in favour of following the Solidity style guide: 

## 📝 Docs

- added Natspec comments for newly created custom errors.
- improve descriptions of existing Natspec docs comments.
    - replace `operation` -> `operationType`.
    - specify "low-level" for call operations + "opcode" for contract creation operations.
operationType
    - add "Requirements" section with bullet points under the `execute(...)` function in the `IERC725X` interface contract.
    
## 🧪 Tests

- edit all revert reason strings with custom errors.

# Gas Cost improvements

2022-10-20 21:45 UTC, YamenMerhi requested changes
Looks good to me, but I would prefer to revert the last commit to keep the checks inside the internal functions. 

The main goal of the internal function is to have every logic + every check of the operation to make inside the relevant internal function, for context reasons, and for future inheritance reasons.

Minor pt:
I prefer the one-line syntax for the revert (if it fits on one line). example:
`if (data.length == 0) revert ERC725X_NoContractBytecodeProvided();` 

instead of:
```
if (data.length == 0) {
     revert ERC725X_NoContractBytecodeProvided();  
}
```

2022-10-20 22:44 UTC, CJ42 commented
> Looks good to me, but I would prefer to revert the last commit to keep the checks inside the internal functions.

The reason I refactored here in this last commit is two fold, First because it found out that it saves 1,309 gas of deployment cost (The contract ends up with more opcodes, likely because there are more stack operations to pass more arguments down to the internal functions). My second reason is explained below.

> The main goal of the internal function is to have every logic + every check of the operation to make inside the relevant internal function, for context reasons, and for future inheritance reasons.

Could you give a bit more the "context and inheritance reasons"?

These my arguments for and against the last commit.

**For reverting the last commit**
- I do agree that the one line `if` statement make it a bit nicer to read. 

**Against reverting the last commit**
- if you look at the refactoring of the internal functions in the last commit, the 3 internal functions for each message calls (`_executeCall(...)`, `_executeStaticCall(...)` and `_executeDelegateCall(...)` now look all the same inside (screenshot below).
- it sounds quite contradictory to create an internal function with a parameter, but this parameter can never be used, because it should always be the same ( `value = 0` for msg calls, and `to = address(0)` for contract deployment). For a dev using the internal function only (_e.g: `_executeStaticCall(...)`), why should it pass an argument to the function if this argument is not used? (here `value` for staticcall).
- since these functions are `virtual`, can't someone have the risk forget to add this check if it overrides?

<img width="718" alt="image" src="https://user-images.githubusercontent.com/31145285/197071251-ccb0aa95-a016-48e0-8f75-ce1283a6eb48.png">

2022-10-20 22:52 UTC, CJ42 commented
@YamenMerhi 

If you look at the equivalent functions from the OpenZeppelin `Address` library , the internal functions `functionStaticCall(...)` and `functionDelegateCall(...)` do not have the `value` parameter.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/a1948250ab8c441f6d327a65754cb20d2b1b4554/contracts/utils/Address.sol#L139-L187

2022-10-20 23:25 UTC, CJ42 commented on implementations/contracts/ERC725XCore.sol
>          result = Address.verifyCallResult(success, returnData, "ERC725X: Unknown Error");
@YamenMerhi I am happy to revert back the last commit if we decide to keep the old structure of the internal functions.

The only extra change I would suggest is to change the revert error message passed to the OZ `Address.sol` library to use the same one they have.

So replace for instance `ERC725X: Unknown Error` > `ERC725X: low-level static call failed`

<img width="867" alt="Screenshot 2022-10-21 at 00 23 04" src="https://user-images.githubusercontent.com/31145285/197077415-1100b83d-5734-4fcc-8f53-1e60c0686fa5.png">

2022-10-21 08:08 UTC, YamenMerhi commented
My main idea was to have every check related to the execution in the internal function so that later if someone wants to implement these execution features they have the checks already in and don't need to add them again. For instance in LSP9Vault, then we need to re-write the logic in the main function again like this: 

```js
if (operationType == uint256(OPERATION_TYPE.STATICCALL)) {
            if (value != 0) revert ERC725X_MsgValueDisallowedInStaticCall();
            return _executeStaticCall(to, data);
        }
        
        if (operationType == uint256(OPERATION_TYPE.CALL)) {
            return _executeCall(to, value, data);
        }
        

        if (operationType == uint256(OPERATION_TYPE.CREATE)) {
            if (to != address(0)) revert ERC725X_CreateOperationsRequireEmptyRecipientAddress();
            return _deployCreate(value, data);
        }

```

instead of doing this:

```js
     If (operationType == uint256(OPERATION_TYPE.STATICCALL)) return _executeStaticCall(to, data);
        
        if (operationType == uint256(OPERATION_TYPE.CALL)) return _executeCall(to, value, data);
        

        if (operationType == uint256(OPERATION_TYPE.CREATE)) return _deployCreate(value, data);

```
But in the end, it's a minor pt, I am happy also to keep it like you change it now.

2022-10-21 09:16 UTC, YamenMerhi approved these changes

2022-10-21 09:26 UTC, skimaharvey approved these changes

2022-10-21 14:14 UTC, frozeman approved these changes

2022-10-21 14:16 UTC, CJ42 commented
As discussed, we remove the `enum` and change back to `OPERATION_0_CALL`, ... (the operation number in the constant name).

2022-10-21 15:33 UTC, merged