ERC725 Update
ERC725Alliance/ERC725 pull request #56
Opened 2021-09-23 12:06 UTC by YamenMerhi

ERC725Alliance Repo Update:
- Changed setData from `calldata` to `memory`
- Took the change of matt regarding the format of the test suite and the names `ERC725YReader/Writer` instead of `Dummy`
- Added revert on failed call + return bytes
- Added helper contract to test ^ these extra features
- Added `universalReceiver` function to ERC725Account and keys needed in constructor
- Added `ERC725Utils` library to make ERC725Account able to set `UniversalReceiverDelegate Key`
- Extended return value of universalReceiver from `bytes32` to `bytes`
- Added Dummy UniversalReceiver to test the function
- Seperated `ERC725X` and `ERC725Y` tests from ERC725Account test
- Fixed the tests to `create2` in ERC725X (was hardcoded without any referance , i implemented `eth-create2-calculator` package)
- Deleted KeyManager and related tests `(ERC734)`
- Calculated `165 interface id`

2021-09-23 13:42 UTC, YamenMerhi commented
@frozeman @CJ42 We should discuss `calldata` to `memory` not just in ERC725Y

2021-09-23 16:07 UTC, frozeman commented on implementations/contracts/ERC725/ERC725Account.sol
> +                returnValue = ILSP1Delegate(universalReceiverAddress).universalReceiverDelegate(
Did you test it it fails? On revert inside the ur delegate. Contract ?

2021-09-23 16:14 UTC, frozeman commented on implementations/contracts/ERC725/IERC725X.sol
> +    ) external payable returns(bytes memory);
Could you also update the ERC725 docs adding the bytes array and return values? Maybe first make the or to this repo before we do at the eip

2021-09-24 11:49 UTC, frozeman commented on implementations/contracts/ERC725/ERC725XCore.sol
>          bytes calldata _data
memory

2021-09-28 11:15 UTC, CJ42 commented
We aWould be better to rename the folder **ILSP1** to **interfaces**.

2021-09-28 11:42 UTC, frozeman commented on implementations/contracts/ERC725/ERC725X.sol
>          bytes calldata _data
we wanted to change this as well to memory as we discussed

2021-09-28 11:43 UTC, frozeman commented on implementations/contracts/ERC725/ERC725XInit.sol
>          bytes calldata _data
Why do we copy and paste here? we shouldn't use copy and pasted code between normal and init.

2021-09-28 11:46 UTC, frozeman requested changes
Please check the comments

2021-09-29 07:15 UTC, frozeman approved these changes
ill merge this and we do the inheritance change in another PR

2021-09-29 07:15 UTC, merged